Article Web Page
MasterLeiva/Microverse-Trials-Review pull request #1
Opened 2023-04-04 21:38 UTC by MasterLeiva

### Article layout
- Use of semantic tags
- Navigation bar
- GitHub flow
- Use of "ul" tags
- Use of anchor tags

2023-04-04 22:54 UTC, MasterLeiva commented
Hi @MasterLeiva , 

Great Job with the project!
However, some issues still need to be addressed but you are almost there!

<img src="https://media.giphy.com/media/znopkG3Fd8ki8IuSba/giphy.gif?cid=ecf05e47j79llqy3qm6nxikx4bb0ctvdz3yfmof6hlar1ean&rid=giphy.gif&ct=g"/>

## Highlights
- ✅ Good use of HTML semantic tags
- ✅ Use of ul lists
- ✅ Working links
- ✅ Great HTML structure

## Required Changes  ↺

- [ ] Please make sure you add linters to your project since it is part of the GitHub flow.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- [ ] Instead of using pixel values, try using relative values like vh or wh for a more responsive website on different screen sizes.
- [ ] Try making your font sizes, colors, and styles more consistent to get more clean design.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-04-04 23:25 UTC, MasterLeiva reviewed
Hi @MasterLeiva , 

Great Job with the project!
However, some issues still need to be addressed. You are almost there! 

<img src="https://media.giphy.com/media/znopkG3Fd8ki8IuSba/giphy.gif?cid=ecf05e47j79llqy3qm6nxikx4bb0ctvdz3yfmof6hlar1ean&rid=giphy.gif&ct=g"/>

## Highlights
- ✅ Good use of HTML semantic tags
- ✅ Working links
- ✅ Professional README format

## Required Changes  ↺

- [ ] Please make sure you add linters to your project since it is part of the GitHub flow.
- [ ] Please remember that all linters need to be passing the tests so that you can move on to the next project.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- [ ] Instead of using pixel values, try using relative values like vh or wh for a more responsive website on different screen sizes.
- [ ] Try making your font sizes, colors, and styles more consistent to get more clean design.
- [ ] As a kindly suggestion, If you are going to declare classes and IDs, make sure to use them instead of the plain tag so that your project can look cleaner and more professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-04-04 23:25 UTC, MasterLeiva commented on index.html
> +      <a href="#electronic_instruments" class="nav-link">Electronic Instruments</a>
Please make sure you use a "ul" tag and each anchor inside of the "li" tags. You can later use Flexbox to improve your design.

2023-04-04 23:44 UTC, OyePriscilla requested changes
Hi @MasterLeiva 👏 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Good use of summary template and inline comment ✔️ 
Good use of GitHub inline comment feature ✔️ 

## Required Changes ♻️

**- [ ] Please kindly add at least one more comment to meet up with the project requirement. 👍** 
<img width="778" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/229945434-31045c4d-0179-4200-b39d-9b08b6fbb59a.png">

- [ ] Please kindly rephrase the underlined sentences below politely as suggestions instead of orders. Then, it will be more informative to always give reasons for required changes, 👍 

<img width="606" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/229945986-ee8e2815-630a-4e46-a903-c53b1613b091.png">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 23:44 UTC, OyePriscilla commented on index.html
> +      <a href="#electronic_instruments" class="nav-link">Electronic Instruments</a>
- [ ] Awesome! Kindly please give reason for the suggested change, it may be obvious to you and not so for others. 👍

2023-04-05 00:15 UTC, MasterLeiva commented on index.html
> +      <header>Music</header>
As a kindly suggestion, please remember we use "h" tags for titles, we use headers for the introductory content of the website, like a section tag but for the introduction.
example:
`<h1>Music</h1>`
Currently all your titles are using the header tag instead of the h tags, almost there, just a little bit more 🙌🏼

2023-04-05 00:21 UTC, MasterLeiva commented on index.html
> +      <header>Music</header>
As a kindly suggestion, please remember we use "h" tags for titles, we use headers for the introductory content of the website, like a section tag but for the introduction.
example:
`<h1>Music</h1>`
Currently, all your titles are using the header tag instead of the h tags, almost there, just a little bit more 🙌🏼

2023-04-05 00:23 UTC, MasterLeiva commented on index.html
> +      <header>Music</header>
As a kindly suggestion, please remember we use "h" tags for titles, we use headers for the introductory content of the website, like a section tag but for the introduction.
example:
`<h1>Music</h1>`
Currently, all your titles are using the header tag instead of the h tags, almost there, just a little bit more 🙌🏼

2023-04-05 19:36 UTC, MasterLeiva reviewed
Hi @MasterLeiva , 

Great Job with the project!
However, some issues still need to be addressed. You are almost there! 

<img src="https://media.giphy.com/media/znopkG3Fd8ki8IuSba/giphy.gif?cid=ecf05e47j79llqy3qm6nxikx4bb0ctvdz3yfmof6hlar1ean&rid=giphy.gif&ct=g"/>

## Highlights
- ✅ Good use of HTML semantic tags
- ✅ Working links
- ✅ Professional README format

## Required Changes  ↺

- [ ] Please make sure you add linters to your project since it is part of the GitHub flow.
- [ ] Please remember that all linters need to be passing the tests so that you can move on to the next project.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- [ ] Instead of using pixel values, try using relative values like vh or wh for a more responsive website on different screen sizes.
- [ ] Try making your font sizes, colors, and styles more consistent to get more clean design.
- [ ] As a kindly suggestion, If you are going to declare classes and IDs, make sure to use them instead of the plain tag so that your project can look cleaner and more professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-04-05 19:36 UTC, MasterLeiva commented on index.html
> +      <header>Music</header>
As a kindly suggestion, please remember we use "h" tags for titles, we use headers for the introductory content of the website, like a section tag but for the introduction.
example:
`<h1>Music</h1>`
Currently, all your titles are using the header tag instead of the h tags, almost there, just a little bit more 🙌🏼

2023-04-05 19:36 UTC, MasterLeiva commented on index.html
> +      <a href="#electronic_instruments" class="nav-link">Electronic Instruments</a>
Please make sure you use a "ul" tag and each anchor inside of the "li" tags for better accessibility and better semantic practice. You can later use Flexbox to improve your design.

2023-04-05 19:46 UTC, huseyinbiyik approved these changes
Hi @MasterLeiva 

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- You used a polite language and explained the reasons for the requested changes 👍 
- Great implementation of the requested changes of previous reviewers 🕸️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 20:44 UTC, merged